apiVersion: v1
kind: Pod
metadata:
  name: patroni
  labels:
    app: postgresql
spec:
  volumes:
  - name: dbvol
    hostPath:
      path: "/var/pgdata/"
  containers:
  - name: postgresql
    image: jberkus/patroni-atomic
    ports:
    - containerPort: 5432
    - containerPort: 8001
    command: [ "/bin/bash", "/scripts/entrypoint.sh" ]
    env:
    - name: CLUSTER
      value: atomic01
    - name: APIUSER
      value: patroni
    - name: APIPASS
      value: patroni
    - name: ETCD
      value: 172.31.43.178
    - name: ADMINUSER
      value: admin
    - name: ADMINPASS
      value: admin
    - name: PGVERSION
      value: "9.5"
    volumeMounts:
    - mountPath: "/pgdata/data"
      name: dbvol
      readOnly: false
