apiVersion: v1
kind: ReplicationController
metadata:
  name: patroni
  labels:
    app: patroni
    role: node
spec:
  replicas: 3
  selector:
    app: postgresql
    role: node
  template:
    metadata:
      name: postgresql
      labels:
        app: postgresql
        role: node
    spec:
      containers:
        - name: postgresql
          image: jberkus/patroni-node
          ports:
          - name: database-port
            containerPort: 5432
          - name: patroni-api
            containerPort: 8001
          env:
          - name: CLUSTER
            valueFrom:
              configMapKeyRef:
                name: patroni-config
                key: cluster
          - name: APIUSER
            valueFrom:
              configMapKeyRef:
                name: patroni-config
                key: apiuser
          - name: APIPASS
            valueFrom:
              configMapKeyRef:
                name: patroni-config
                key: apipass
          - name: ETCD
            valueFrom:
              configMapKeyRef:
                name: patroni-config
                key: etcd
          - name: ADMINUSER
            valueFrom:
              configMapKeyRef:
                name: patroni-config
                key: adminuser
          - name: ADMINPASS
            valueFrom:
              configMapKeyRef:
                name: patroni-config
                key: adminpass
