apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  selector:
    component: "{{.Release.Name}}-{{.Values.Component}}"
  ports:
  - port: 5432
  clusterIP: None

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
  annotations:
    "helm.sh/created": {{ .Release.Time.Seconds | quote }}
spec:
  serviceName: {{ template "fullname" . }}
  replicas: {{default 5 .Values.Replicas }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}-{{.Values.Component}}"
      annotations:
        "helm.sh/created": {{.Release.Time.Seconds | quote }}
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: citus
        image: "{{ .Values.Citus.Image }}:{{ .Values.Citus.Version }}"
        env:
        - name: POD_GROUP
          value: {{ template "fullname" . }}
        - name: SET_SIZE
          value: "{{default 5 .Values.Replicas }}"
        - name: SUPERPASS
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: password-superuser
        - name: ADMINPASS
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: password-admin
        - name: REPPASS
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: password-standby
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: LANG
          value: C.UTF8
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: "{{.Values.Resources.Cpu}}"
            memory: "{{.Values.Resources.Memory}}"
        volumeMounts:
        - name: pgdata
          mountPath: /pgdata
        - mountPath: /tmp/citus
          name: citus-config
          readOnly: true
      volumes:
      - name: citus-config
        secret:
          secretName: {{ template "fullname" . }}
volumeClaimTemplates:
- metadata:
    name: pgdata
    annotations:
      volume.alpha.kubernetes.io/storage-class: anything
  spec:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: "{{.Values.Resources.Storage}}"
