apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-query
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  selector:
    component: "{{.Release.Name}}-{{.Values.Component}}"
    citus-role: query
  ports:
  - port: 5432
