apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: patroni
  labels:
    component: patroni-patroni
spec:
  serviceName:
  replicas: 3
  template:
    metadata:
      name: patroni
      labels:
        component: patroni-patroni
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: spilo
        image: registry.opensource.zalan.do/acid/spilo-9.5:1.1-p5
        env:
        - name: PGPASSWORD_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: patroni
              key: password-superuser
        - name: PGPASSWORD_ADMIN
          valueFrom:
            secretKeyRef:
              name: patroni
              key: password-admin
        - name: PGPASSWORD_STANDBY
          valueFrom:
            secretKeyRef:
              name: patroni
              key: password-standby
        - name: ETCD_DISCOVERY_DOMAIN
          value: etcd-client.svc.cluster.local
        - name: SCOPE
          value: cluster01
        - name: USE_WALE
          value: "false"
        - name: PGROOT
          value: /home/postgres/pgdata/pgroot
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8008
        - containerPort: 5432
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: pgdata
          mountPath: /home/postgres/pgdata
        - mountPath: /etc/patroni
          name: patroni-config
          readOnly: true
      volumes:
      - name: patroni-config
        secret:
          secretName: patroni
  volumeClaimTemplates:
  - metadata:
      name: pgdata
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
