kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgdata
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-492250fd
    fsType: ext4
